### ISSUE TITLE
No longer compatible with Java 6?

### ISSUE THREAD

**Issue by brunchboy** [TheClimateCorporation/claypoole#31]
It seems that as of version 1.1.1, Claypoole can no longer be used in Java 1.6 environments, even though Clojure itself still compiles to Java 6 compatible class files. There must be some other compiled code which is included and which is being compiled to a newer class file format?

I noticed because after upgrading my [afterglow-max](https://github.com/brunchboy/afterglow-max#afterglow-max) package to include my latest release of Afterglow, which included Claypoole 1.1.1, it would no longer load within Max/MSP (which is, sadly, forever stuck using Apple’s Java 6).

I was able to work around it by building with an exclusion and pulling in the 1.1.0 version of Claypoole for afterglow-max, but I was wondering if this was intentional?

**Comment by leon-barrett** [comment]
Sorry, that's accidental. Let me see if I can rebuild easily for java 1.6.

**Comment by leon-barrett** [comment]
Rebuilt as version 1.1.2. Does that work for you? Also, let me see if I can keep this from happening again.

**Comment by brunchboy** [comment]
Thanks, updating afterglow to depend on 1.1.2 did the trick, and I no longer need an exclusion to keep Claypoole back at 1.1.0 for afterglow-max.

I know Java 6 is ridiculously old, but there are still a few environments where it is the only option, much to my dismay. Cycling ’74, the creators of Max/MSP, are choosing to simply discontinue Java support entirely once the next Mac OS X release drops support for the old Apple Java 6 implementation, rather than invest in updating to a modern Oracle JVM. So afterglow-max will cease to be relevant at that point.
