### ISSUE TITLE
pmap docstring refers to :cpu argument (should be :builtin)? 

### ISSUE THREAD

**Issue by jwvdm** [TheClimateCorporation/claypoole#32]
The docstring for `pmap` appears to be out of date. This docstring states that the `:cpu` keyword can be used as an argument for `pool`. It however appears that `:cpu` has been replaced by the `:builtin` keyword.

Many thanks for developing this very useful library!

**Comment by leon-barrett** [comment]
Oh, thanks, good catch. I'll get on that!
