### ISSUE TITLE
Blog posting is missing

### ISSUE THREAD

**Issue by akond** [TheClimateCorporation/claypoole#41]
http://eng.climate.com/2014/02/25/claypoole-threadpool-tools-for-clojure mentioned in the README gives a 404 page.

**Comment by leon-barrett** [comment]
Thanks for letting me know. I'll add a copy from the Wayback Machine soon. For now you can see it at https://web.archive.org/web/20160318005532/http://eng.climate.com/2014/02/25/claypoole-threadpool-tools-for-clojure/

**Comment by leon-barrett** [comment]
Thanks; I've just copied it into a doc directory. Thanks for letting me know about the broken link! Let me know if you find the result unsatisfactory.
